version: '3'

services:
  # SQL Server
  azuresqledge:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      - MSSQL_SA_PASSWORD=Rewards.Docker1!
      - ACCEPT_EULA=1
    ports:
      - 1433:1433
  
  # Azurite
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002

  # API
  webapi:
    depends_on:
      - azuresqledge
    build:
      dockerfile: src/WebAPI/Dockerfile
    ports:
      - 5001:5001
      - 81:81
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5001;http://+:81
      - ASPNETCORE_Kestrel__Certificates__Default__Password=ThisPassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/WebAPI.pfx
    volumes:
       - ~/.aspnet/https:/https:ro
    profiles: ['all', 'webapi']
    

  # Admin UI
  adminui:
    depends_on:
      - azuresqledge
    build:
      dockerfile: src/AdminUI/Dockerfile
      args:
        - BUILD_CONFIGURATION=DEBUG
    ports:
      - 80:80
      - 7137:7137
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:7137;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=ThisPassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/WebAPI.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    profiles: ['all', 'admin']