parameters:
  ArtifactName:
  WorkingDirectory:
  StageName:

stages:
- stage: ${{parameters.StageName}}
  displayName: Build and Publish artifacts
  jobs:
  - job: BuildAndPublishBlazorUI
    displayName: Build and Publish artifacts
    steps:
    - template: build-blazor-ui-tasks.yml
      parameters:
        ArtifactName: ${{parameters.ArtifactName}}
        BuildId: $(Build.BuildId)
        WorkingDirectory: ${{parameters.WorkingDirectory}}
