parameters:
  ArtifactName:
  WorkingDirectory:

stages:
- stage: BuildUI
  displayName: Build Blazor UI and Publish artifacts
  jobs:
  - job: BuildAndPublishBlazorUI
    displayName: Build and Publish artifacts
    steps:
    - template: build-blazor-ui-tasks.yml
      parameters:
        ArtifactName: ${{parameters.ArtifactName}}
        BuildId: $(Build.BuildId)
        WorkingDirectory: ${{parameters.WorkingDirectory}}
