parameters:
  ArtifactName:
  WorkingDirectory:

stages:
- stage: BuildUI
  displayName: Build Blazor UI and Publish artifacts
  jobs:
  - job: BuildAndPublishBlazorUI
    displayName: Build Blazor UI and publish artifacts
    steps:
    - template: build-blazor-ui-tasks.yml
      parameters:
        ArtifactName: $(ArtifactName)
        BuildId: $(Build.BuildId)
        WorkingDirectory: $(WorkingDirectory)
