parameters:
  AzureSubscriptionName:
  EnvironmentName:
  ArtifactName:
  DependsOnStageName:

stages:
- stage: ${{parameters.EnvironmentName}}
  dependsOn: ${{parameters.DependsOnStageName}}
  jobs:
  - deployment: DeployAdminUI
    environment: ${{parameters.EnvironmentName}}
    pool:
      vmImage: 'ubuntu-latest'
    variables:
    # Load the environment specific azure infrastructure variable groups
    # e.g. Dev-infra, Staging-infra, Prod-infra
    - group: '${{parameters.EnvironmentName}}-infra'
    
    # IMPORTANT: This is the naming convention for resource groups
    # - e.g. SSW.Consulting.Dev, SSW.Consulting.Staging, SSW.Consulting.Prod
    - name: resourceGroupName
      value: 'SSW.Consulting.${{parameters.EnvironmentName}}'
    
    strategy:
      runOnce:
        deploy:
          steps:
          - template: deploy-ui-to-static-website-tasks.yml
            parameters:
              AzureSubscriptionName: ${{parameters.AzureSubscriptionName}}
              ResourceGroupName: $(resourceGroupName)
              StaticSiteAccountName: $(AdminStaticSiteAccountName)
              StaticSiteAccountKey: $(AdminStaticSiteAccountKey)
              ArtifactName: '$(Pipeline.Workspace)/$(ArtifactName)'
