parameters:
  AzureSubscriptionName:
  EnvironmentName:
  ArtifactName:
  SourcePath:
  DependsOnStageName:
  ProjectName:

stages:
- stage: ${{parameters.EnvironmentName}}
  dependsOn: ${{parameters.DependsOnStageName}}
  displayName: Deploy ${{parameters.ProjectName}} to ${{parameters.EnvironmentName}}
  # prevent deployment on PullRequest builds (Reason != PullRequest)
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  jobs:
  - deployment: Deploy
    environment: ${{parameters.EnvironmentName}}
    pool:
      vmImage: 'ubuntu-latest'
    variables:
    # Load the environment specific azure infrastructure variable groups
    # e.g. Dev-infra, Staging-infra, Prod-infra
    - group: ${{parameters.EnvironmentName}}-infra
    
    # IMPORTANT: This is the naming convention for resource groups
    # - e.g. SSW.Consulting.Dev, SSW.Consulting.Staging, SSW.Consulting.Prod
    - name: resourceGroupName
      value: SSW.Consulting.${{parameters.EnvironmentName}}
    
    strategy:
      runOnce:
        deploy:
          steps:
          - template: deploy-ui-to-static-website-tasks.yml
            parameters:
              AzureSubscriptionName: ${{parameters.AzureSubscriptionName}}
              ResourceGroupName: $(resourceGroupName)
              StaticSiteAccountName: $(AdminStaticSiteAccountName)
              StaticSiteAccountKey: $(AdminStaticSiteAccountKey)
              ArtifactName: '$(Pipeline.Workspace)/${{parameters.ArtifactName}}'
              SourcePath: ${{parameters.SourcePath}}
          
          - template: purge-cdn.yml
            parameters:
              AzureSubscriptionName: ${{parameters.AzureSubscriptionName}}
              ResourceGroupName: $(resourceGroupName)
              CdnEndpointName: $(CdnEndpointName)
              CdnProfileName: $(CdnProfileName)
