trigger:
  branches:
    include:
      - master
  paths:
    include:
      - "/Blazor/*"

pool:
  vmImage: "ubuntu-latest"

variables:
  system.debug: true
  agent.diagnostic: true

stages:
  - template: ./templates/build-ui-stage.yml
    displayName: Build Blazor UI and Publish artifacts
    parameters:
      WorkingDirectory: $(System.DefaultWorkingDirectory)/Blazor
      BlazorProjectFile: SSW.Rewards.Admin.csproj
      ArtifactName: adminUI

  - template: ./templates/deploy-ui-stage.yml
    displayName: Deploy Blazor UI to Dev
    # prevent deployment on PullRequest builds (Reason != PullRequest)
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    parameters:
      EnvironmentName: Dev
      AzureSubscriptionName: "SSW.Consulting.Dev"
      DependsOnStageName: BuildUI
      ArtifactName: adminUI

# - template: ./templates/deploy-ui-stage.yml
#   displayName: Deploy Blazor UI to Prod
#   condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
#   parameters:
#     EnvironmentName: Prod
#     AzureSubscriptionName: 'SSW.Consulting.Prod'
#     DependsOnStageName: Dev
#     ArtifactName: adminUI
