trigger:
  branches:
    include:
      - master
  paths:
    include:
      - "/Blazor/*"

pool:
  vmImage: "ubuntu-latest"

variables:
  system.debug: true
  agent.diagnostic: true

stages:
  - template: ./templates/build-ui-stage.yml
    parameters:
      WorkingDirectory: $(System.DefaultWorkingDirectory)/Blazor
      BlazorProjectFile: SSW.Rewards.Admin.csproj
      ArtifactName: adminUI

  - template: ./templates/deploy-ui-stage.yml
    parameters:
      EnvironmentName: Dev
      AzureSubscriptionName: "SSW.Consulting.Dev"
      DependsOnStageName: BuildUI
      ArtifactName: adminUI
# - template: ./templates/deploy-ui-stage.yml
#   parameters:
#     EnvironmentName: Prod
#     AzureSubscriptionName: 'SSW.Consulting.Prod'
#     DependsOnStageName: Dev
#     ArtifactName: adminUI
