name: Admin - Main (Build & Deploy)

on:
  push:
    branches: 
      - main
    paths-ignore:
      - .github/settings.yml

  workflow_dispatch:

jobs:
  admin-build:
    uses: ./.github/workflows/build-artifact.yml
    with:
      project_path: src/Presentation/UI/AdminUI/AdminUI.csproj

  deploy_dev:
    name: Admin - Deploy
    needs: build
    uses: ./.github/workflows/admin-deploy.yml
    with:
      environment: dev
      resourceGroupName: ssw.rewards.dev
    secrets: inherit

  deploy_staging:
     name: Admin - Deploy Staging
     needs: deploy_dev
     uses: ./.github/workflows/admin-deploy.yml
     with:
       environment: staging
       resourceGroupName: ssw.rewards.staging
     secrets: inherit

  deploy_prod:
     name: Admin - Deploy Prod
     needs: deploy_staging
     uses: ./.github/workflows/admin-deploy.yml
     with:
       environment: prod
       resourceGroupName: ssw.rewards.prod
     secrets: inherit
