name: Admin - Main (Build & Deploy)

on:
  workflow_dispatch:

jobs:
  admin_build:
    uses: ./.github/workflows/admin-build.yml

  deploy_dev:
    name: Admin - Deploy
    needs: admin_build
    uses: ./.github/workflows/admin-deploy.yml
    with:
      environment: dev
      resourceGroupName: ssw.rewards.dev
    secrets: inherit

  deploy_staging:
     name: Admin - Deploy Staging
     needs: deploy_dev
     uses: ./.github/workflows/admin-deploy.yml
     with:
       environment: staging
       resourceGroupName: ssw.rewards.staging
     secrets: inherit

  deploy_prod:
     name: Admin - Deploy Prod
     needs: deploy_staging
     uses: ./.github/workflows/admin-deploy.yml
     with:
       environment: prod
       resourceGroupName: ssw.rewards.prod
     secrets: inherit
