name: Build Android app

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      build_number:
        required: true
        type: string
    # secrets:
    #   android_keystore:
    #     required: true
    #   android_keystore_password:
    #     required: true

jobs:
  build:
    runs-on: windows-latest
    environment: ${{ inputs.environment }}
    name: Android Build

    steps:
      - uses: actions/checkout@v3

      - name: Use build number
        run: |
          $buildNumber=${{ inputs.build_number }}
          echo "Build Number: $buildNumber"

      - name: Update Build Number
        run: |
          $content = Get-Content src/MobileUI/MobileUI.csproj -Raw

          $newContent = $content -replace '<ApplicationVersion>.*</ApplicationVersion>', "<ApplicationVersion>$buildNumber</ApplicationVersion>"

          Set-Content src/MobileUI/MobileUI.csproj -Value $newContent

      - name: Setup DotNet Environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Install MAUI Workload
        run: |
          dotnet nuget locals all --clear
          dotnet workload install maui --ignore-failed-sources
          dotnet workload install android maui wasm-tools --source https://api.nuget.org/v3/index.json

      - name: Restore Dependencies
        run: |
          dotnet restore SSW.Rewards.sln

      - name: Publish Android Mobile App
        run: |
          dotnet publish src/MobileUI/MobileUI.csproj -c:Release -f:net8.0-android --no-restore /p:AndroidPackageFormat="aab"

      # Store Android Signing Keystore and password in Secrets using base64 encoding
      # https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/certutil
      # command line util to encode to base64 on windows
      - name: Extract Android signing key from env
        shell: bash
        run: |
          cd src/MobileUI
          mkdir android
          echo "${{ secrets.android_keystore }}" > android/sswrewards.jks.base64
          base64 -d android/sswrewards.jks.base64 > android/sswrewards.decrypted.jks
      # check android SDK paths etc in installed VM : https://github.com/actions/virtual-environments#available-environments
      - name: Sign dev build
        shell: bash
        run: |
          cd src/MobileUI
          jarsigner -keystore android/sswrewards.decrypted.jks -storepass "${{ secrets.android_keystore_password }}" -signedjar bin/Release/net8.0-android/publish/com.ssw.consulting-Signed.aab bin/Release/net8.0-android/publish/com.ssw.consulting.aab key

      - uses: actions/upload-artifact@v3.1.2
        with:
          name: artifacts-android-${{ inputs.build_number }}
          path: |
            src\MobileUI\bin\Release\net8.0-android\publish\*.aab
