name: API - Build

on:
  workflow_call:

env:
  PROJECT_PATH: src/Presentation/WebAPI/WebAPI.csproj

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'
      
      - name: Install dependencies
        run: dotnet restore $PROJECT_PATH
      - name: Build
        run: dotnet build $PROJECT_PATH  --configuration Release --no-restore
      - name: Test
        run: dotnet test $PROJECT_PATH  --configuration Release --no-build
      - name: Publish
        run: dotnet publish $PROJECT_PATH --configuration Release --no-build --output ./published
      - name: Zip
        shell: pwsh
        run: Compress-Archive -Path ./published/* -DestinationPath ./api.zip
      
      # api 
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: api
          path: ./api.zip
          retention-days: 2
      # infra
      - name: Upload Infra Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: infra
          path: ./infra
          retention-days: 2