name: Build iOS app

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      build_number:
        required: true
        type: string

jobs:
  build:
    runs-on: macos-13
    environment: ${{ inputs.environment }}
    name: iOS Build

    steps:
      - uses: actions/checkout@v3

      - name: Update Build Number
        run: sed -i '' "s|<ApplicationVersion>.*</ApplicationVersion>|<ApplicationVersion>${{ inputs.build_number }}</ApplicationVersion>|g" src/MobileUI/MobileUI.csproj

      - name: Setup DotNet Environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Install MAUI Workload
        run: |
          dotnet nuget locals all --clear
          dotnet workload install maui --ignore-failed-sources
          dotnet workload install ios maui wasm-tools --source https://api.nuget.org/v3/index.json --ignore-failed-sources

      - name: Set XCode Version
        if: runner.os == 'macOS'
        shell: bash
        run: |
          sudo xcode-select -s "/Applications/Xcode_15.1.app"
          echo "MD_APPLE_SDK_ROOT=/Applications/Xcode_15.1.app" >> $GITHUB_ENV

      - name: Import Code-Signing Certificates
        uses: Apple-Actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.IOS_SIGNING_CERTIFICATE }}
          p12-password: ${{ secrets.IOS_SIGNING_CERTIFICATE_PASSWORD }}

      - name: Download Apple Provisioning Profiles
        uses: Apple-Actions/download-provisioning-profiles@v1
        with:
          bundle-id: "com.SSW.SSW.Consulting"
          profile-type: "IOS_APP_STORE"
          issuer-id: ${{ secrets.APPLE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPLE_KEY_ID }}
          api-private-key: ${{ secrets.APPLE_KEY }}

      - name: Build MAUI iOS
        run: dotnet publish src/MobileUI/MobileUI.csproj -c Release -f net8.0-ios -r ios-arm64 --self-contained /p:buildForSimulator=False /p:packageApp=True /p:ArchiveOnBuild=true /p:EnableAssemblyILStripping=true /p:PublishTrimmed=true

      - name: Upload iOS Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: artifacts-ios-${{ inputs.build_number }}
          path: MobileUI/bin/Release/net8.0-ios/ios-arm64/publish//*.ipa
