
name: Build and deploy

on:
  workflow_dispatch:
  push:
    branches: 
      - main
    paths-ignore:
      - .github/settings.yml

jobs:
  build-api:
    name: Build and upload artifacts
    uses: ./.github/workflows/build.yml
  
  deploy_staging_api:
    needs: build-api
    name: Deploy staging
    uses: ./.github/workflows/az-deploy.yml
    with:
      ENVIRONMENT: staging
      RESOURCE_GROUP: SSW.Rewards.Staging
      APP_SERVICE_PLAN: plan-ssw-shared-dev
      APP_SERVICE_PLAN_RESOURCE_GROUP: SSW.AppServicePlans
      ADMIN_PORTAL_URL: https://staging.rewards.ssw.com.au
      IDS_URL: https://app-ssw-ident-staging-api.azurewebsites.net
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      SQL_ADMIN_GROUP: ${{ secrets.SQL_ADMIN_GROUP }}
      SQL_ADMIN_GROUP_SID: ${{ secrets.SQL_ADMIN_GROUP_SID }}
      # GRAPH_TENANT_ID: ${{ secrets.GRAPH_TENANT_ID }}
      # GRAPH_CLIENT_ID: ${{ secrets.GRAPH_CLIENT_ID }}
      # GRAPH_CLIENT_SECRET: ${{ secrets.GRAPH_CLIENT_SECRET }}

  deploy_prod_api:
    needs: deploy_staging_api
    name: Deploy prod
    uses: ./.github/workflows/az-deploy.yml
    with:
      ENVIRONMENT: prod
      RESOURCE_GROUP: SSW.Rewards.Prod
      APP_SERVICE_PLAN: plan-ssw-shared-prod
      APP_SERVICE_PLAN_RESOURCE_GROUP: SSW.AppServicePlans
      ADMIN_PORTAL_URL: https://rewards.ssw.com.au
      IDS_URL: https://identity.ssw.com.au
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      SQL_ADMIN_GROUP: ${{ secrets.SQL_ADMIN_GROUP }}
      SQL_ADMIN_GROUP_SID: ${{ secrets.SQL_ADMIN_GROUP_SID }}
      # GRAPH_TENANT_ID: ${{ secrets.GRAPH_TENANT_ID }}
      # GRAPH_CLIENT_ID: ${{ secrets.GRAPH_CLIENT_ID }}
      # GRAPH_CLIENT_SECRET: ${{ secrets.GRAPH_CLIENT_SECRET }}

  build-admin:
    uses: ./.github/workflows/build.yml
    with:
      publishProjectPath: src/UI/UI.csproj

  deploy_dev_admin:
    name: Deploy
    needs: build-admin
    uses: ./.github/workflows/deploy.yml
    with:
      environment: dev
      resourceGroupName: ssw.rewards.dev
    secrets: inherit

  deploy_staging_admin:
     name: Deploy Staging
     needs: deploy_dev_admin
     uses: ./.github/workflows/deploy.yml
     with:
       environment: staging
       resourceGroupName: ssw.rewards.staging
     secrets: inherit

  deploy_prod_admin:
     name: Deploy Prod
     needs: deploy_staging_admin
     uses: ./.github/workflows/deploy.yml
     with:
       environment: prod
       resourceGroupName: ssw.rewards.prod
     secrets: inherit
     